# Generated by Django 3.2.6 on 2021-08-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_no', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('disrict', models.CharField(max_length=100)),
            ],
        ),
    ]
