# Generated by Django 3.2.6 on 2021-08-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerregistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='disrict',
            new_name='district',
        ),
    ]
