# Generated by Django 3.2.6 on 2021-08-12 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customerregistration', '0002_rename_disrict_customer_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
